using System;

class Foo : Exception
{
}

class Bar : Foo
{
}

class Cleanup
{
	public Cleanup(int y_) : y(y_) 
	{
	}
	public ~Cleanup()
	{
		Console.Out() << "cleanup: y=" << y << endl();
	}
	private int y;
}

void throw_foo()
{
	throw Foo();
}

void ex()
{
	int x = 1234;
	try
	{
		int y = 9999;
		try
		{
			Cleanup cu(y);
			throw_foo();
		}
		catch (const Bar& bar)
		{
			Console.Out() << "wrong handler!" << endl();
		}
	}
	catch (const Foo& foo)
	{
		Console.Out() << foo.ToString() << "\n:(x=" << x << ")" << endl();
		throw;
	}
}

int main()
{
	try
	{
		ex();
	}
	catch (const Foo& foo)
	{
		Console.Error() << foo.ToString() << endl();
		return 1;
	}
	return 0;
}
