using System;

class Foo : Exception
{
}

class Bar : Foo
{
}

class Cleanup
{
	public Cleanup(int y_) : y(y_) 
	{
	}
	public ~Cleanup()
	{
		string s = "cleanup: y=" + ToString(y) + "\n";
		write(1, s.Chars(), s.Length());
	}
	private int y;
}

void throw_foo()
{
	throw Foo();
}

void ex()
{
	int x = 1234;
	try
	{
		int y = 9999;
		try
		{
			Cleanup cu(y);
			throw_foo();
		}
		catch (const Bar& bar)
		{
			string s = "wrong handler!\n";
			write(1, s.Chars(), s.Length());
		}
	}
	catch (const Foo& foo)
	{
		string s = foo.ToString() + "(x=" + ToString(x) + ")\n";
		write(1, s.Chars(), s.Length());
		throw;
	}
}

int main()
{
	try
	{
		ex();
	}
	catch (const Foo& foo)
	{
		string s = foo.ToString() + "\n";
		write(1, s.Chars(), s.Length());
		return 1;
	}
	return 0;
}
