using System;
using System.IO;

void main()
{
    try
    {
        int x = 0;
    }
    catch (const Exception& ex)
    {
        Console.Error() << ex.Message() << endl();
    }
}
